### ISSUE TITLE
White text on white background for "Sponsored by"

### ISSUE THREAD

**Issue by borisschapira** [edgemesh/crux.run#6]
On every `[data-page="api.md"]` route, the EdgeMesh link is white on white.

![Capture d’écran 2019-09-16 à 13 44 56](https://user-images.githubusercontent.com/284742/64955916-bd538f80-d889-11e9-8cb0-1a1925f4bffd.png)

**Comment by SupremeTechnopriest** [comment]
Thanks for catching this @borisschapira! I'm on it!

**Comment by SupremeTechnopriest** [comment]
New docs for v1 just released!  This bug is fixed.  Thanks again!
